"""add payment intents"""
from alembic import op
import sqlalchemy as sa
revision = '1e37a7efe47c'
down_revision = '9abcabbc6e55'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_request_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=80), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=80), nullable=True),
    sa.Column('result_code', sa.String(length=30), nullable=True),
    sa.Column('result_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_checkout_request_id'), 'payment_intents', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_customer_id'), 'payment_intents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_repair_request_id'), 'payment_intents', ['repair_request_id'], unique=True)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_repair_request_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_customer_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_checkout_request_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    # ### end Alembic commands ###
