"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision = '9abcabbc6e55'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index(op.f('ix_providers_verified'), 'providers', ['verified'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('serial_last4', sa.String(length=4), nullable=True),
    sa.Column('imei_last4', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_customer_id'), 'devices', ['customer_id'], unique=False)
    op.create_table('technician_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('background_verified', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_profiles_available'), 'technician_profiles', ['available'], unique=False)
    op.create_index(op.f('ix_technician_profiles_user_id'), 'technician_profiles', ['user_id'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_technician_id'), 'credentials', ['technician_id'], unique=False)
    op.create_table('repair_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('issue', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('service_mode', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_requests_customer_id'), 'repair_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_device_id'), 'repair_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_status'), 'repair_requests', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_request_id', sa.String(length=36), nullable=False),
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('parts_amount', sa.Integer(), nullable=False),
    sa.Column('labour_amount', sa.Integer(), nullable=False),
    sa.Column('callout_amount', sa.Integer(), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('part_tier', sa.String(length=30), nullable=False),
    sa.Column('customer_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_repair_request_id'), 'quotes', ['repair_request_id'], unique=False)
    op.create_index(op.f('ix_quotes_technician_id'), 'quotes', ['technician_id'], unique=False)
    op.create_table('repair_inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_request_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('screen_ok', sa.Boolean(), nullable=False),
    sa.Column('camera_ok', sa.Boolean(), nullable=False),
    sa.Column('face_id_ok', sa.Boolean(), nullable=False),
    sa.Column('speaker_ok', sa.Boolean(), nullable=False),
    sa.Column('microphone_ok', sa.Boolean(), nullable=False),
    sa.Column('charging_ok', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_inspections_repair_request_id'), 'repair_inspections', ['repair_request_id'], unique=False)
    op.create_table('repair_passport_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('repair_request_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_passport_events_device_id'), 'repair_passport_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_repair_passport_events_repair_request_id'), 'repair_passport_events', ['repair_request_id'], unique=False)
    op.create_table('warranties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repair_request_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_request_id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranties')
    op.drop_index(op.f('ix_repair_passport_events_repair_request_id'), table_name='repair_passport_events')
    op.drop_index(op.f('ix_repair_passport_events_device_id'), table_name='repair_passport_events')
    op.drop_table('repair_passport_events')
    op.drop_index(op.f('ix_repair_inspections_repair_request_id'), table_name='repair_inspections')
    op.drop_table('repair_inspections')
    op.drop_index(op.f('ix_quotes_technician_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_repair_request_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_repair_requests_status'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_device_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_customer_id'), table_name='repair_requests')
    op.drop_table('repair_requests')
    op.drop_index(op.f('ix_credentials_technician_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_technician_profiles_user_id'), table_name='technician_profiles')
    op.drop_index(op.f('ix_technician_profiles_available'), table_name='technician_profiles')
    op.drop_table('technician_profiles')
    op.drop_index(op.f('ix_devices_customer_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_verified'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
